### ISSUE TITLE
Calibration: "ERROR: Turntable failed to home, setting random home position"

### ISSUE THREAD

**Issue by momfertje** [DCC-EX/EX-Turntable#52]
Calibration cycle still returns `ERROR: Turntable failed to home, setting random home position` in version 0.2.3

How to reproduce:

1. Update config.h to use `#define STEPPER_DRIVER ULN2003_HALF_CW`  or `#define STEPPER_DRIVER ULN2003_HALF_CCW` and save
2. Erase the EEPROM with sketch from IDE
3. Remove HAL sensor to prevent successful homing/calibration cycle
4. Upload Turntable-EX
5. Open IDE Serial Monitor
6. Cyclus starts with 
`Turntable-EX has not been calibrated yet`
`Calibrating...`
`Homing started`
7. Wait until calibration cycle is ended and returns
`ERROR: Turntable failed to home, setting random home position`

**Comment by peteGSX** [comment]
FYI I'm still not able to replicate this, but I think we leave this issue open while Beta testing commences and see if others experience it also.
